version: '3'
services:
  jenkins:
    build: .
    image: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
          - ./jenkins_home:/var/jenkins_home
          - ./data:/data
     #     - ~/.m2/repository:/m2/repository
       #   - /var/run/docker.sock:/var/run/docker.sock
